version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend-placa-ocr
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./best1.pt:/app/best1.pt
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload 